version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: tola_postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mycryptodb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
